services:

  database:
    build: database
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD=mysecretpassword
    networks:
      - database
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql

  cql-on-omop:
    build: cql-on-omop
    env_file: databases.env
    stop_signal: SIGQUIT
    networks:
      - database
    depends_on:
      - database

networks:
  database:
    external: no

volumes:
  data:
    external: no
